language: ruby
rvm:
  - 2.1.0
  - 2.0.0
gemfile:
  - Gemfile
branches:
  only:
    - devel
    - /^fix_.*$/
    - /^feat_.*$/
matrix:
  include:
    - rvm: 2.2.0
      env: REDMINE_VERSION=3.1-stable USE_SVN=true DATABASE_ADAPTER=mysql
      gemfile: Gemfile
    - rvm: 2.2.0
      env: REDMINE_VERSION=3.1-stable USE_SVN=true DATABASE_ADAPTER=postgresql
      gemfile: Gemfile
    - rvm: 2.2.0
      env: REDMINE_VERSION=3.0-stable USE_SVN=true DATABASE_ADAPTER=mysql
      gemfile: Gemfile
    - rvm: 2.2.0
      env: REDMINE_VERSION=3.0-stable USE_SVN=true DATABASE_ADAPTER=postgresql
      gemfile: Gemfile
    - rvm: 2.2.0
      env: REDMINE_VERSION=3.0.5 DATABASE_ADAPTER=mysql
      gemfile: Gemfile
    - rvm: 2.2.0
      env: REDMINE_VERSION=3.0.5 DATABASE_ADAPTER=postgresql
      gemfile: Gemfile
    - rvm: 2.2.0
      env: REDMINE_VERSION=3.1.1 DATABASE_ADAPTER=mysql
      gemfile: Gemfile
    - rvm: 2.2.0
      env: REDMINE_VERSION=3.1.1 DATABASE_ADAPTER=postgresql
      gemfile: Gemfile
env:
  global:
    - REDMINE_LANG=en
    - MYSQL_DATABASE=redmine
    - MYSQL_HOST=127.0.0.1
    - MYSQL_PORT=3306
    - MYSQL_USER=root
    - MYSQL_PASSWORD=
    - POSTGRES_DATABASE=redmine
    - POSTGRES_USER=postgres
  matrix:
    - REDMINE_VERSION=3.1-stable USE_SVN=true DATABASE_ADAPTER=mysql
    - REDMINE_VERSION=3.1-stable USE_SVN=true DATABASE_ADAPTER=postgresql
    - REDMINE_VERSION=3.0-stable USE_SVN=true DATABASE_ADAPTER=mysql
    - REDMINE_VERSION=3.0-stable USE_SVN=true DATABASE_ADAPTER=postgresql
    - REDMINE_VERSION=2.6-stable USE_SVN=true DATABASE_ADAPTER=mysql
    - REDMINE_VERSION=2.6-stable USE_SVN=true DATABASE_ADAPTER=postgresql

    - REDMINE_VERSION=3.1.1 DATABASE_ADAPTER=mysql
    - REDMINE_VERSION=3.1.1 DATABASE_ADAPTER=postgresql
    - REDMINE_VERSION=3.0.5 DATABASE_ADAPTER=mysql
    - REDMINE_VERSION=3.0.5 DATABASE_ADAPTER=postgresql
    - REDMINE_VERSION=2.6.7 DATABASE_ADAPTER=mysql
    - REDMINE_VERSION=2.6.7 DATABASE_ADAPTER=postgresql

    # - REDMINE_VERSION=3.1.0 DATABASE_ADAPTER=mysql
    # - REDMINE_VERSION=3.1.0 DATABASE_ADAPTER=postgresql
    # - REDMINE_VERSION=3.0.4 DATABASE_ADAPTER=mysql
    # - REDMINE_VERSION=3.0.4 DATABASE_ADAPTER=postgresql
    # - REDMINE_VERSION=2.6.6 DATABASE_ADAPTER=mysql
    # - REDMINE_VERSION=2.6.6 DATABASE_ADAPTER=postgresql
    # - REDMINE_VERSION=3.0.3 DATABASE_ADAPTER=mysql
    # - REDMINE_VERSION=3.0.3 DATABASE_ADAPTER=postgresql
    # - REDMINE_VERSION=2.6.5 DATABASE_ADAPTER=mysql
    # - REDMINE_VERSION=2.6.5 DATABASE_ADAPTER=postgresql
    # - REDMINE_VERSION=3.0.2 DATABASE_ADAPTER=mysql
    # - REDMINE_VERSION=3.0.2 DATABASE_ADAPTER=postgresql
    # - REDMINE_VERSION=2.6.4 DATABASE_ADAPTER=mysql
    # - REDMINE_VERSION=2.6.4 DATABASE_ADAPTER=postgresql
    # - REDMINE_VERSION=3.0.1 DATABASE_ADAPTER=mysql
    # - REDMINE_VERSION=3.0.1 DATABASE_ADAPTER=postgresql
    # - REDMINE_VERSION=2.6.3 DATABASE_ADAPTER=mysql
    # - REDMINE_VERSION=2.6.3 DATABASE_ADAPTER=postgresql
    # - REDMINE_VERSION=3.0.0 DATABASE_ADAPTER=mysql
    # - REDMINE_VERSION=3.0.0 DATABASE_ADAPTER=postgresql
    # - REDMINE_VERSION=2.6.2 DATABASE_ADAPTER=mysql
    # - REDMINE_VERSION=2.6.2 DATABASE_ADAPTER=postgresql
    # - REDMINE_VERSION=2.6.1 DATABASE_ADAPTER=mysql
    # - REDMINE_VERSION=2.6.1 DATABASE_ADAPTER=postgresql
    # - REDMINE_VERSION=2.6.0 DATABASE_ADAPTER=mysql
    # - REDMINE_VERSION=2.6.0 DATABASE_ADAPTER=postgresql
    # - REDMINE_VERSION=2.5.3 DATABASE_ADAPTER=mysql
    # - REDMINE_VERSION=2.5.3 DATABASE_ADAPTER=postgresql
    # - REDMINE_VERSION=2.5.2 DATABASE_ADAPTER=mysql
    # - REDMINE_VERSION=2.5.2 DATABASE_ADAPTER=postgresql
    # - REDMINE_VERSION=2.5.1
    # - REDMINE_VERSION=2.5.0
    # - REDMINE_VERSION=2.4.7 DATABASE_ADAPTER=mysql
    # - REDMINE_VERSION=2.4.7 DATABASE_ADAPTER=postgresql
    # - REDMINE_VERSION=2.4.6 DATABASE_ADAPTER=mysql
    # - REDMINE_VERSION=2.4.6 DATABASE_ADAPTER=postgresql
    # - REDMINE_VERSION=2.4.5
    # - REDMINE_VERSION=2.4.4
    # - REDMINE_VERSION=2.4.3
    # - REDMINE_VERSION=2.4.2
    # - REDMINE_VERSION=2.4.1
    # - REDMINE_VERSION=2.4.0
    # - REDMINE_VERSION=2.3.4
    # - REDMINE_VERSION=2.2.4
before_install:
  - cd ../..
  - sudo apt-get update -qq
  - ./jbox-web/redmine_git_hosting/contrib/travis/install_redmine.sh
  - cd redmine
  - echo $(pwd)
  - export BUNDLE_GEMFILE=$PWD/Gemfile
before_script:
  - echo $(pwd)
  - mysql -e 'create database redmine;'
  - psql -c 'create database redmine;' -U postgres
  - bundle exec rake generate_secret_token
  - bundle exec rake db:migrate
  - bundle exec rake redmine:load_default_data
  - bundle exec rake redmine:plugins:migrate
  - bundle exec rake db:test:prepare
script:
  - bundle exec rake redmine_git_hosting:ci:all
