language: ruby
sudo: required
cache: bundler
rvm:
  - 2.6.3
  - 2.4.6
  - 2.3.8
gemfile:
  - Gemfile
services:
  - mysql
  - postgresql
branches:
  only:
    - devel
    - /^fix_.*$/
    - /^feat_.*$/
env:
  global:
    - REDMINE_LANG=en
    - MYSQL_DATABASE=redmine
    - MYSQL_HOST=127.0.0.1
    - MYSQL_PORT=3306
    - MYSQL_USER=root
    - MYSQL_PASSWORD=
    - POSTGRES_DATABASE=redmine
    - POSTGRES_USER=postgres
  matrix:
    - REDMINE_VERSION=4.0-stable DATABASE_ADAPTER=mysql USE_SVN=true
    - REDMINE_VERSION=4.0-stable DATABASE_ADAPTER=postgresql USE_SVN=true
before_install:
  - cd ../..
  - sudo apt-get update -qq
  - ./jbox-web/redmine_git_hosting/contrib/travis/install_redmine.sh
  - cd redmine
  - echo $(pwd)
  - export BUNDLE_GEMFILE=$PWD/Gemfile
before_script:
  - echo $(pwd)
  - mysql -e 'create database redmine;'
  - psql -c 'create database redmine;' -U postgres
  - bundle exec rake generate_secret_token
  - bundle exec rake db:migrate
  - bundle exec rake redmine:load_default_data
  - bundle exec rake redmine:plugins:migrate
  - bundle exec rake db:test:prepare
script:
  - bundle exec rake redmine_git_hosting:ci:all
